#!/usr/bin/env ruby
require 'daemons'
require 'tin_can'

# Quiet some warnings we see when running in warning mode:
# RUBYOPT=-w bundle exec sidekiq
DEBUG = ENV['DEBUG']

begin
  TinCan.load_environment
  Daemons.run_proc('tin_can') do
    TinCan.start
  end
rescue => e
  raise e if DEBUG
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
