#!/usr/bin/env ruby
require 'daemons'
require 'tin_can'

# Quiet some warnings we see when running in warning mode:
# RUBYOPT=-w bundle exec sidekiq
DEBUG = ENV['DEBUG']

begin
  case ARGV[0]
  when 'start'
    puts 'Loading environment...'
    TinCan.load_environment
  when 'stop'
    puts 'Stopping tin-can...'
  end

  options = {
    app_name: 'tin-can',
    multiple: false,
    backtrace: true,
    monitor: true,
    dir_mode: :script,
    dir: 'tmp/pids/',
    log_output: true,
    log_dir: 'log/',
    output_logfilename: 'tin-can.log',
  }
  Daemons.run_proc('tin-can', options) do
    TinCan.start
  end
rescue => e
  raise e if DEBUG
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
